### ISSUE TITLE
[v1.4] type declaration of $xpath of WebDriver setValue as string is incompatible with Behat CoreDriver

### ISSUE THREAD

**Issue by Caster000** [oleg-andreyev/MinkWebdriver#91]
Hello,
I'am using the WebDriver with Behat and with the recent update v1.4 to support PHP8 I noticed an incompatibility with the Behat\Mink\Driver\CoreDriver on the setValue function.

Here is the error: 
`PHP Fatal error:  Declaration of OAndreyev\Mink\Driver\WebDriver::setValue(string $xpath, mixed $value): void must be compatible with Behat\Mink\Driver\CoreDriver::setValue($xpath, $value) in /vendor/oleg-andreyev/mink-phpwebdriver/src/WebDriver.php on line 673`

To solve the issue I think that we must keep the type declaration of $xpath as mixed.
https://github.com/oleg-andreyev/MinkPhpWebDriver/blame/b5db536639157567ad7b2dcc8e67506d31e7e7df/src/WebDriver.php#L675

For precision, I am using PHP8.3

**Comment by oleg-andreyev** [comment]
I'll take a look, interesting that static analysis didn't catch it

**Comment by oleg-andreyev** [comment]
@Caster000 which version of behat/mink, `composer info behat/mink` ? Lowest behat/mink:v1.11.0 already has `public function setValue(string $xpath, $value)`

**Comment by Caster000** [comment]
@oleg-andreyev indeed you are right. I forgot to precise that we are using the friendOfBehat fork : https://github.com/FriendsOfBehat/Mink. Which is not up to date. But was at the time we started our project.
So your implementation is right, I'll check to use the official behat/mink that seems to be maintained again.
Thanks for the help!

**Comment by oleg-andreyev** [comment]
@Caster000 please install new version
